<header style="
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 20px;
  background: #546E7A;
  color: white;
">

  <div class="header-left">
    <h1 style="
      margin-right: 10px;
    ">Numpy</h1>
  </div>
</header>

<hr>

# making arrays 

In [1]:
import numpy as np
import random

In [8]:
# 1d array (vector)
x = [2, 3, 5, 7, 11]
numbers = np.array(x)  
numbers

array([ 2,  3,  5,  7, 11])

In [3]:
type(numbers), numbers

(numpy.ndarray, array([ 2,  3,  5,  7, 11]))

In [4]:
numbers.dtype

dtype('int32')

In [6]:
#  2d  array
np.array([[1, 2, 3], [4, 5, 6]])    

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
a = [1, 2]
np.asarray(a)

array([1, 2])

In [12]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.ones_like(numbers)

array([1, 1, 1, 1, 1])

In [15]:
zero = np.zeros(4, dtype=int)
zero

array([0, 0, 0, 0])

<p style='background-color:#FDD835;color:black;border-radius:10px;margin:5px;padding:5px;'>
zeroes and zeroes_like are as same as ones and ones_like except use zero instead of one
</p>

In [20]:
np.empty(10).astype(int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [21]:
full = np.full((3,5), 25)
full

array([[25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25]])

In [22]:
full.ndim

2

In [26]:
linspace = np.linspace(20, 50, 8)
linspace

array([20.        , 24.28571429, 28.57142857, 32.85714286, 37.14285714,
       41.42857143, 45.71428571, 50.        ])

# data types

In [27]:
numbers.dtype

dtype('int32')

In [28]:
floats = np.array([[0.2, 0.3, 0.4],[0.5, 0.6, 0.7]])
floats

array([[0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7]])

In [29]:
floats.dtype

dtype('float64')

<img src='dtypes.png' style='border: 5px solid #555;' width=70% align=left>

In [5]:
## Type casting

t_change = np.array(numbers, dtype=float)
print(t_change)
t_change.dtype

[ 2.  3.  5.  7. 11.]


dtype('float64')

In [ ]:
np.empty(10).astype(int)

# dimensions and size of arrays

In [30]:
floats.ndim   #its means floats array is 2d array

2

In [31]:
 numbers.ndim  #its means numbers array is 1d array

1

In [32]:
floats.shape

(2, 3)

In [33]:
numbers.shape

(5,)

<p style='background-color:#FDD835;color:black;border-radius:10px;margin:5px;padding:5px;'>
    diffrence beetwen ndim and shape is ndim return exacly dimensions number but shape return a tuple and vectors of each dimensions
</p>

# processing arrays

In [38]:
# not recommended way
for row in floats :
    for col in row :
        print(col, end='  ')
    print()

0.2  0.3  0.4  
0.5  0.6  0.7  


In [39]:
for i in floats.flat:   # flat make n-d arrays to a vector
    print(i, end='  ')

0.2  0.3  0.4  0.5  0.6  0.7  

# making special arrays 

In [40]:
linspace.reshape(2,2,2)   # be careful mul of reshape args must be equal with arrays  size

array([[[20.        , 24.28571429],
        [28.57142857, 32.85714286]],

       [[37.14285714, 41.42857143],
        [45.71428571, 50.        ]]])

In [50]:
z = np.arange(6)#.reshape(3,1,2)
z.reshape(3,2,1)

array([[[0],
        [1]],

       [[2],
        [3]],

       [[4],
        [5]]])

# list or array(speed test)


In [51]:
%timeit python_rolls_list = [random.randrange(1,7) for i in range(0, 6000)]

6.42 ms ± 121 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [52]:
%timeit numpy_rolls_list = np.random.randint(1, 7, 6000)

115 µs ± 518 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


# operations

<img src='1.jpg' style='border: 5px solid #555;' width=70% align=left>
<img src='2.jpg' style='border: 5px solid #555;' width=70% align=left>

In [53]:
numbers
numbers >= 5

array([False, False,  True,  True,  True])

In [10]:
a=np.random.rand(2,2)
b=np.random.rand(2,2)
print('a: ',a)
print('b : ', b,'\n')
print('element-wise : ',a*b,'\n')
print('matrix mult',a@b,)
np.dot(a, b)
np.dot(a, b) == a@b
np.dot(a, b) is a@b

a:  [[0.95129655 0.01187968]
 [0.13851414 0.00928922]]
b :  [[0.98090947 0.96781753]
 [0.78899467 0.39539561]] 

element-wise :  [[0.93313579 0.01149736]
 [0.10928692 0.00367292]] 

matrix mult [[0.9425088  0.92537865]
 [0.14319897 0.13772933]]


False

In [11]:
a@b.shape

array([1.92635246, 0.29560671])

In [12]:
np.dot(a, b)

array([[0.9425088 , 0.92537865],
       [0.14319897, 0.13772933]])

In [14]:
grades = np.linspace(20, 50, 12, dtype= int).reshape(4, 3)
grades.sum()
grades.min()
grades.max()
grades.mean()
grades.std()
grades.var()

89.40972222222223

# axis

<img src='axis.png' style='border: 5px solid #555;' width=70% align=left>

In [ ]:
grades.mean(axis=0 , dtype=int)

array([32, 34, 37])

In [ ]:
grades.std(axis=1)

array([2.05480467, 2.05480467, 2.05480467, 2.44948974])

In [ ]:
np.sqrt(grades.mean(axis=0 , dtype=int))

array([5.65685425, 5.83095189, 6.08276253])

# slicing

In [15]:
grades

array([[20, 22, 25],
       [28, 30, 33],
       [36, 39, 41],
       [44, 47, 50]])

In [ ]:
grades[1, 2]  # row=0, col=1

33

In [ ]:
grades[1]   #row =1

array([28, 30, 33])

In [ ]:
grades[1:3] #col=1,2

array([[28, 30, 33],
       [36, 39, 41]])

In [ ]:
grades[:,0]   # its mean that all first col elements

array([20, 28, 36, 44])

In [ ]:
grades[:,1:3]

array([[22, 25],
       [30, 33],
       [39, 41],
       [47, 50]])

In [ ]:
grades[:,[1,2]]

array([[22, 25],
       [30, 33],
       [39, 41],
       [47, 50]])

# view and copy 

<p style="background-color: #FDD835;color:#000;border-radius:10px;margin:5px;padding:5px;">
    The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.
The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.
</p>

In [56]:
nums = np.arange(1,7).reshape(2,3)
nums

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
nums2 = nums.view()
nums2

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
nums2[1, 2] = 7
nums

array([[1, 2, 3],
       [4, 5, 7]])

In [59]:
nums3 = nums.copy()
nums3[1, 2] = 8
nums

array([[1, 2, 3],
       [4, 5, 7]])

In [61]:
nums is nums3

False

# transpose

In [62]:
x = np.arange(4).reshape((2,2))
np.transpose(x)

array([[0, 2],
       [1, 3]])

In [63]:
x = np.ones((1, 2, 3))
np.transpose(x, (1, 0, 2)).shape

(2, 1, 3)